@extends('layouts.app')
@section('content')
<div class="page-heading"><div><div class="eyebrow">PANEL GENERAL</div><h1>Buenos días, María <span class="heading-wave">✦</span></h1><p class="lead-copy">Aquí tienes el estado de la operación para hoy.</p></div><button class="btn btn-primary"><i class="bi bi-plus-lg"></i> Crear turno</button></div>
<div class="alert-banner"><i class="bi bi-info-circle-fill"></i><span><strong>La cobertura de hoy está al 92%.</strong> Hay 3 turnos que requieren atención antes de las 14:00.</span><a href="{{ route('shifts') }}">Revisar turnos <i class="bi bi-arrow-right"></i></a></div>
<div class="stats-grid"><div class="stat-card"><div class="stat-icon red"><i class="bi bi-calendar-check"></i></div><span>Turnos de hoy</span><strong>24</strong><small class="positive"><i class="bi bi-arrow-up"></i> 8% <em>vs. ayer</em></small></div><div class="stat-card"><div class="stat-icon blue"><i class="bi bi-people"></i></div><span>Personas activas</span><strong>86</strong><small class="positive"><i class="bi bi-arrow-up"></i> 12% <em>este mes</em></small></div><div class="stat-card"><div class="stat-icon orange"><i class="bi bi-hospital"></i></div><span>Sedes operativas</span><strong>12</strong><small class="neutral">En 3 municipios</small></div><div class="stat-card"><div class="stat-icon green"><i class="bi bi-shield-check"></i></div><span>Cobertura promedio</span><strong>92<small class="percent">%</small></strong><small class="positive"><i class="bi bi-arrow-up"></i> 4% <em>esta semana</em></small></div></div>
<div class="section-row"><div class="section-title"><h2>Actividad de hoy</h2><span class="status-pill">Actualizado hace 5 min</span></div><a class="text-link" href="{{ route('shifts') }}">Ver todos <i class="bi bi-arrow-right"></i></a></div>
<div class="content-grid"><div class="panel schedule-panel"><div class="panel-head"><div><h3>Turnos próximos</h3><p>Martes 24 de septiembre, 2026</p></div><button class="filter-button">Hoy <i class="bi bi-chevron-down"></i></button></div><div class="shift-list"><div class="shift-item"><div class="shift-time">08:00 <small>AM</small></div><div class="shift-line"></div><div class="shift-info"><strong>Triaje general</strong><span><i class="bi bi-hospital"></i> Hospital San Gabriel</span></div><span class="tag tag-red">En curso</span><div class="stacked-avatars"><span>AC</span><span>LM</span><span>+2</span></div></div><div class="shift-item"><div class="shift-time">10:30 <small>AM</small></div><div class="shift-line muted"></div><div class="shift-info"><strong>Atención primaria</strong><span><i class="bi bi-house-heart"></i> Refugio La Esperanza</span></div><span class="tag tag-green">Completo</span><div class="stacked-avatars"><span>JR</span><span>CM</span><span>+4</span></div></div><div class="shift-item"><div class="shift-time">14:00 <small>PM</small></div><div class="shift-line muted"></div><div class="shift-info"><strong>Triaje pediátrico</strong><span><i class="bi bi-hospital"></i> Hospital San Gabriel</span></div><span class="tag tag-yellow">1 vacante</span><div class="stacked-avatars"><span>SP</span><span>+3</span></div></div><div class="shift-item"><div class="shift-time">18:00 <small>PM</small></div><div class="shift-line muted"></div><div class="shift-info"><strong>Apoyo logístico</strong><span><i class="bi bi-house-heart"></i> Refugio Los Pinos</span></div><span class="tag tag-green">Completo</span><div class="stacked-avatars"><span>NV</span><span>+5</span></div></div></div></div><div class="panel coverage-panel"><div class="panel-head"><div><h3>Cobertura por sede</h3><p>Estado actual</p></div><button class="more-button"><i class="bi bi-three-dots"></i></button></div><div class="coverage-chart"><div class="donut"><strong>92<small>%</small></strong><span>cobertura</span></div><div class="legend"><span><i class="dot red-dot"></i> Hospitales <b>95%</b></span><span><i class="dot orange-dot"></i> Refugios <b>88%</b></span><span><i class="dot gray-dot"></i> En revisión <b>3</b></span></div></div><a class="coverage-link" href="{{ route('sites') }}">Ver detalle de sedes <i class="bi bi-arrow-up-right"></i></a></div></div>
<div class="section-row mt-5"><div class="section-title"><h2>Alertas que requieren atención</h2><span class="count-pill">3</span></div><a class="text-link" href="{{ route('availability') }}">Gestionar disponibilidad <i class="bi bi-arrow-right"></i></a></div><div class="alert-list"><div><i class="bi bi-exclamation-triangle-fill warning-icon"></i><span><strong>Falta cobertura en triaje pediátrico</strong><small>Hospital San Gabriel · Hoy, 14:00 - 18:00</small></span><a href="{{ route('shifts') }}">Resolver</a></div><div><i class="bi bi-moon-stars-fill rest-icon"></i><span><strong>Descanso pendiente de confirmar</strong><small>4 personas tienen solapamiento de turnos</small></span><a href="{{ route('people') }}">Revisar</a></div></div>
@endsection
